Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: S3TriggerExampleFunction
      Handler: index.handler
      Runtime: nodejs14.x
      Role: arn:aws:iam::000000000000:role/lambda-role
      Code:
        ZipFile: |
          exports.handler = async (s3Event) => {
            console.log(JSON.stringify(s3Event));
          }

  # Create our S3 bucket, pre-configured to invoke our Lambda.
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: eventbucket                   # CHANGE THIS
      NotificationConfiguration:
        LambdaConfigurations:
        - Event: "s3:ObjectCreated:*"
          Function: !GetAtt LambdaFunction.Arn