dags:
  gitSync:
    enabled: true
    repo: git@github.com:tymob0/airflow-k8s-playground.git
    branch: main
    subPath: ''
    sshKeySecret: airflow-ssh-secret
    period: 0.1s
image:
  repository: customairflow
  tag: v3
  pullPolicy: IfNotPresent
extraEnv: |
- name: AIRFLOW__API__AUTH_BACKENDS
  value: 'airflow.api.auth.backend.basic_auth'
extraSecrets:
  airflow-ssh-secret:
    data: |
      gitSshKey: <<<YOUR_SSH_KEY>>>
